import { Category, CategoryInfo } from '@/types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'food_dining', label: 'Food & Dining', color: '#f97316', icon: 'UtensilsCrossed' },
  { id: 'groceries', label: 'Groceries', color: '#84cc16', icon: 'ShoppingCart' },
  { id: 'shopping', label: 'Shopping', color: '#8b5cf6', icon: 'ShoppingBag' },
  { id: 'transportation', label: 'Transportation', color: '#3b82f6', icon: 'Car' },
  { id: 'subscriptions', label: 'Subscriptions', color: '#ec4899', icon: 'RefreshCw' },
  { id: 'bills_utilities', label: 'Bills & Utilities', color: '#6366f1', icon: 'Zap' },
  { id: 'entertainment', label: 'Entertainment', color: '#f43f5e', icon: 'Gamepad2' },
  { id: 'health_fitness', label: 'Health & Fitness', color: '#10b981', icon: 'Heart' },
  { id: 'travel', label: 'Travel', color: '#0ea5e9', icon: 'Plane' },
  { id: 'income', label: 'Income', color: '#22c55e', icon: 'TrendingUp' },
  { id: 'transfer', label: 'Transfer', color: '#94a3b8', icon: 'ArrowLeftRight' },
  { id: 'other', label: 'Other', color: '#64748b', icon: 'MoreHorizontal' },
];

export const MERCHANT_KEYWORDS: Record<string, Category> = {
  // Food & Dining - Restaurants, fast food, coffee, delivery
  'doordash': 'food_dining',
  'uber eats': 'food_dining',
  'ubereats': 'food_dining',
  'grubhub': 'food_dining',
  'postmates': 'food_dining',
  'caviar': 'food_dining',
  'seamless': 'food_dining',
  'mcdonalds': 'food_dining',
  "mcdonald's": 'food_dining',
  'starbucks': 'food_dining',
  'sbux': 'food_dining',
  'chipotle': 'food_dining',
  'subway': 'food_dining',
  'dominos': 'food_dining',
  "domino's": 'food_dining',
  'panera': 'food_dining',
  'chick-fil-a': 'food_dining',
  'chickfila': 'food_dining',
  'wendys': 'food_dining',
  "wendy's": 'food_dining',
  'taco bell': 'food_dining',
  'dunkin': 'food_dining',
  'pizza hut': 'food_dining',
  'panda express': 'food_dining',
  'five guys': 'food_dining',
  'shake shack': 'food_dining',
  'sweetgreen': 'food_dining',
  'cava': 'food_dining',
  'toast restaurant': 'food_dining',
  'tst': 'food_dining',
  'toast': 'food_dining',
  'restaurant': 'food_dining',
  'cafe': 'food_dining',
  'coffee': 'food_dining',
  'bistro': 'food_dining',
  'grill': 'food_dining',
  'kitchen': 'food_dining',
  'diner': 'food_dining',
  'pizzeria': 'food_dining',
  'bakery': 'food_dining',
  'brewery': 'food_dining',
  'bar ': 'food_dining',
  'pub ': 'food_dining',
  'tavern': 'food_dining',
  'sushi': 'food_dining',
  'ramen': 'food_dining',
  'burger': 'food_dining',
  'tacos': 'food_dining',
  'wings': 'food_dining',
  'bbq': 'food_dining',
  'steakhouse': 'food_dining',
  'seafood': 'food_dining',
  'eatery': 'food_dining',
  'juice bar': 'food_dining',
  'smoothie': 'food_dining',
  'ice cream': 'food_dining',
  'dessert': 'food_dining',

  // Groceries
  'whole foods': 'groceries',
  'wholefds': 'groceries',
  'trader joe': 'groceries',
  "trader joe's": 'groceries',
  'safeway': 'groceries',
  'kroger': 'groceries',
  'costco': 'groceries',
  'aldi': 'groceries',
  'publix': 'groceries',
  'wegmans': 'groceries',
  'sprouts': 'groceries',
  'h-e-b': 'groceries',
  'heb': 'groceries',
  'food lion': 'groceries',
  'giant': 'groceries',
  'stop & shop': 'groceries',
  'albertsons': 'groceries',
  'instacart': 'groceries',
  'amazon fresh': 'groceries',
  'fresh market': 'groceries',
  'central market': 'groceries',
  'grocery': 'groceries',
  'supermarket': 'groceries',
  'wild alaskan': 'groceries',
  'butcher box': 'groceries',
  'imperfect foods': 'groceries',
  'misfits market': 'groceries',
  'thrive market': 'groceries',

  // Shopping - Retail, clothing, electronics, home goods
  'amazon': 'shopping',
  'amzn': 'shopping',
  'target': 'shopping',
  'walmart': 'shopping',
  'wal-mart': 'shopping',
  'best buy': 'shopping',
  'bestbuy': 'shopping',
  'apple store': 'shopping',
  'apple.com': 'shopping',
  'ebay': 'shopping',
  'etsy': 'shopping',
  'ikea': 'shopping',
  'home depot': 'shopping',
  'lowes': 'shopping',
  "lowe's": 'shopping',
  'wayfair': 'shopping',
  'nordstrom': 'shopping',
  'macys': 'shopping',
  "macy's": 'shopping',
  'kohls': 'shopping',
  "kohl's": 'shopping',
  'tj maxx': 'shopping',
  'marshalls': 'shopping',
  'ross': 'shopping',
  'old navy': 'shopping',
  'gap': 'shopping',
  'zara': 'shopping',
  'h&m': 'shopping',
  'uniqlo': 'shopping',
  'nike': 'shopping',
  'adidas': 'shopping',
  'lululemon': 'shopping',
  'athleta': 'shopping',
  'rei': 'shopping',
  'patagonia': 'shopping',
  'north face': 'shopping',
  'faherty': 'shopping',
  'houndstooth': 'shopping',
  'clothing': 'shopping',
  'apparel': 'shopping',
  'shoes': 'shopping',
  'footwear': 'shopping',
  'jewelry': 'shopping',
  'furniture': 'shopping',
  'mattress': 'shopping',
  'bed bath': 'shopping',
  'pottery barn': 'shopping',
  'crate barrel': 'shopping',
  'west elm': 'shopping',
  'williams sonoma': 'shopping',
  'container store': 'shopping',
  'office depot': 'shopping',
  'staples': 'shopping',
  'michaels': 'shopping',
  'petco': 'shopping',
  'petsmart': 'shopping',
  'chewy': 'shopping',
  'flora': 'shopping',
  'flowers': 'shopping',
  'florist': 'shopping',

  // Transportation - Gas, rideshare, parking, car services
  'uber': 'transportation',
  'lyft': 'transportation',
  'shell': 'transportation',
  'chevron': 'transportation',
  'exxon': 'transportation',
  'mobil': 'transportation',
  'bp': 'transportation',
  'texaco': 'transportation',
  'valero': 'transportation',
  'speedway': 'transportation',
  'wawa': 'transportation',
  'gas': 'transportation',
  'fuel': 'transportation',
  'petroleum': 'transportation',
  'parking': 'transportation',
  'garage': 'transportation',
  'metro': 'transportation',
  'transit': 'transportation',
  'toll': 'transportation',
  'ez pass': 'transportation',
  'car wash': 'transportation',
  'auto repair': 'transportation',
  'tire': 'transportation',
  'jiffy lube': 'transportation',
  'autozone': 'transportation',
  'toyota': 'transportation',

  // Subscriptions - Digital services with recurring charges
  'netflix': 'subscriptions',
  'spotify': 'subscriptions',
  'hulu': 'subscriptions',
  'disney+': 'subscriptions',
  'disney plus': 'subscriptions',
  'hbo': 'subscriptions',
  'hbo max': 'subscriptions',
  'apple music': 'subscriptions',
  'apple tv': 'subscriptions',
  'apple one': 'subscriptions',
  'youtube premium': 'subscriptions',
  'youtube music': 'subscriptions',
  'amazon prime': 'subscriptions',
  'prime video': 'subscriptions',
  'audible': 'subscriptions',
  'adobe': 'subscriptions',
  'microsoft 365': 'subscriptions',
  'office 365': 'subscriptions',
  'dropbox': 'subscriptions',
  'icloud': 'subscriptions',
  'google one': 'subscriptions',
  'chatgpt': 'subscriptions',
  'openai': 'subscriptions',
  'notion': 'subscriptions',
  'figma': 'subscriptions',
  'canva': 'subscriptions',
  'linkedin premium': 'subscriptions',
  'skillshare': 'subscriptions',
  'masterclass': 'subscriptions',
  'duolingo': 'subscriptions',
  'calm': 'subscriptions',
  'headspace': 'subscriptions',
  'nytimes': 'subscriptions',
  'new york times': 'subscriptions',
  'wsj': 'subscriptions',
  'wall street journal': 'subscriptions',
  'paramount': 'subscriptions',
  'peacock': 'subscriptions',
  'espn+': 'subscriptions',
  'xbox game pass': 'subscriptions',
  'playstation plus': 'subscriptions',
  'github': 'subscriptions',
  '1password': 'subscriptions',
  'nordvpn': 'subscriptions',
  'expressvpn': 'subscriptions',
  'brightwheel': 'subscriptions',

  // Bills & Utilities - Phone, internet, electric, insurance
  'at&t': 'bills_utilities',
  'att': 'bills_utilities',
  'verizon': 'bills_utilities',
  't-mobile': 'bills_utilities',
  'tmobile': 'bills_utilities',
  'us mobile': 'bills_utilities',
  'mint mobile': 'bills_utilities',
  'google fi': 'bills_utilities',
  'comcast': 'bills_utilities',
  'xfinity': 'bills_utilities',
  'spectrum': 'bills_utilities',
  'cox': 'bills_utilities',
  'electric': 'bills_utilities',
  'power': 'bills_utilities',
  'energy': 'bills_utilities',
  'water': 'bills_utilities',
  'utility': 'bills_utilities',
  'pge': 'bills_utilities',
  'pg&e': 'bills_utilities',
  'austin energy': 'bills_utilities',
  'geico': 'bills_utilities',
  'state farm': 'bills_utilities',
  'progressive': 'bills_utilities',
  'allstate': 'bills_utilities',
  'liberty mutual': 'bills_utilities',
  'usaa': 'bills_utilities',
  'tesla insurance': 'bills_utilities',
  'tesla property': 'bills_utilities',
  'insurance': 'bills_utilities',
  'rent': 'bills_utilities',
  'mortgage': 'bills_utilities',
  'hoa': 'bills_utilities',

  // Entertainment - Events, movies, games
  'steam': 'entertainment',
  'playstation': 'entertainment',
  'xbox': 'entertainment',
  'nintendo': 'entertainment',
  'movie': 'entertainment',
  'cinema': 'entertainment',
  'theater': 'entertainment',
  'amc': 'entertainment',
  'regal': 'entertainment',
  'concert': 'entertainment',
  'ticketmaster': 'entertainment',
  'stubhub': 'entertainment',
  'eventbrite': 'entertainment',
  'museum': 'entertainment',
  'zoo': 'entertainment',
  'golf': 'entertainment',

  // Health & Fitness
  'gym': 'health_fitness',
  'fitness': 'health_fitness',
  'planet fitness': 'health_fitness',
  'equinox': 'health_fitness',
  'orangetheory': 'health_fitness',
  'crossfit': 'health_fitness',
  'peloton': 'health_fitness',
  'yoga': 'health_fitness',
  'pilates': 'health_fitness',
  'jiu jitsu': 'health_fitness',
  'jiu-jitsu': 'health_fitness',
  'martial arts': 'health_fitness',
  'boxing': 'health_fitness',
  'kingsway': 'health_fitness',
  'cvs': 'health_fitness',
  'walgreens': 'health_fitness',
  'pharmacy': 'health_fitness',
  'doctor': 'health_fitness',
  'medical': 'health_fitness',
  'hospital': 'health_fitness',
  'clinic': 'health_fitness',
  'dental': 'health_fitness',
  'dentist': 'health_fitness',
  'therapist': 'health_fitness',
  'therapy': 'health_fitness',
  'chiropractor': 'health_fitness',
  'massage': 'health_fitness',
  'spa': 'health_fitness',
  'salon': 'health_fitness',
  'haircut': 'health_fitness',
  'barber': 'health_fitness',

  // Travel - Airlines, hotels, car rental
  'airline': 'travel',
  'airlines': 'travel',
  'united': 'travel',
  'delta': 'travel',
  'american air': 'travel',
  'southwest': 'travel',
  'jetblue': 'travel',
  'frontier': 'travel',
  'spirit': 'travel',
  'hotel': 'travel',
  'hotels': 'travel',
  'marriott': 'travel',
  'hilton': 'travel',
  'hyatt': 'travel',
  'four seasons': 'travel',
  'airbnb': 'travel',
  'vrbo': 'travel',
  'booking.com': 'travel',
  'expedia': 'travel',
  'hertz': 'travel',
  'enterprise': 'travel',
  'avis': 'travel',
  'turo': 'travel',
  'amex travel': 'travel',
  'chase travel': 'travel',
  'cruise': 'travel',
  'tsa': 'travel',
  'global entry': 'travel',

  // Income indicators
  'payroll': 'income',
  'direct deposit': 'income',
  'salary': 'income',
  'deposit': 'income',
  'refund': 'income',
  'cashback': 'income',
  'cash back': 'income',
  'reimbursement': 'income',

  // Transfer indicators
  'transfer': 'transfer',
  'xfer': 'transfer',
  'wire': 'transfer',
  'zelle': 'transfer',
  'venmo': 'transfer',
  'paypal': 'transfer',
};

export const MONEY_LEAK_KEYWORDS: { pattern: string; type: string; label: string }[] = [
  // Bank fees
  { pattern: 'overdraft', type: 'bank_fee', label: 'Overdraft Fee' },
  { pattern: 'nsf fee', type: 'bank_fee', label: 'NSF Fee' },
  { pattern: 'insufficient funds', type: 'bank_fee', label: 'Insufficient Funds Fee' },
  { pattern: 'monthly fee', type: 'bank_fee', label: 'Monthly Account Fee' },
  { pattern: 'maintenance fee', type: 'bank_fee', label: 'Account Maintenance Fee' },
  { pattern: 'service fee', type: 'bank_fee', label: 'Service Fee' },
  { pattern: 'service charge', type: 'bank_fee', label: 'Service Charge' },
  { pattern: 'account fee', type: 'bank_fee', label: 'Account Fee' },
  { pattern: 'wire fee', type: 'bank_fee', label: 'Wire Transfer Fee' },
  { pattern: 'paper statement', type: 'bank_fee', label: 'Paper Statement Fee' },

  // ATM fees
  { pattern: 'atm fee', type: 'atm_fee', label: 'ATM Fee' },
  { pattern: 'atm surcharge', type: 'atm_fee', label: 'ATM Surcharge' },
  { pattern: 'non-network atm', type: 'atm_fee', label: 'Out-of-Network ATM' },
  { pattern: 'atm withdraw', type: 'atm_fee', label: 'ATM Withdrawal Fee' },
  { pattern: 'out of network', type: 'atm_fee', label: 'Out-of-Network Fee' },

  // Interest charges
  { pattern: 'interest charge', type: 'interest', label: 'Interest Charge' },
  { pattern: 'finance charge', type: 'interest', label: 'Finance Charge' },
  { pattern: 'interest payment', type: 'interest', label: 'Interest Payment' },
  { pattern: 'purchase interest', type: 'interest', label: 'Purchase Interest' },
  { pattern: 'cash advance interest', type: 'interest', label: 'Cash Advance Interest' },
  { pattern: 'minimum interest', type: 'interest', label: 'Minimum Interest Charge' },

  // Late fees
  { pattern: 'late fee', type: 'late_fee', label: 'Late Fee' },
  { pattern: 'late charge', type: 'late_fee', label: 'Late Charge' },
  { pattern: 'late payment', type: 'late_fee', label: 'Late Payment Fee' },
  { pattern: 'past due', type: 'late_fee', label: 'Past Due Fee' },
  { pattern: 'penalty fee', type: 'late_fee', label: 'Penalty Fee' },

  // Convenience fees
  { pattern: 'convenience fee', type: 'convenience_fee', label: 'Convenience Fee' },
  { pattern: 'processing fee', type: 'convenience_fee', label: 'Processing Fee' },
  { pattern: 'delivery fee', type: 'convenience_fee', label: 'Delivery Fee' },
  { pattern: 'rush fee', type: 'convenience_fee', label: 'Rush Fee' },
  { pattern: 'expedite', type: 'convenience_fee', label: 'Expedite Fee' },

  // Foreign transaction fees
  { pattern: 'foreign transaction', type: 'foreign_fee', label: 'Foreign Transaction Fee' },
  { pattern: 'currency conversion', type: 'foreign_fee', label: 'Currency Conversion Fee' },
  { pattern: 'intl fee', type: 'foreign_fee', label: 'International Fee' },
  { pattern: 'exchange fee', type: 'foreign_fee', label: 'Exchange Fee' },
];

