import { Category, CategoryInfo } from '@/types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'food_dining', label: 'Food & Dining', color: '#f97316', icon: 'UtensilsCrossed' },
  { id: 'groceries', label: 'Groceries', color: '#84cc16', icon: 'ShoppingCart' },
  { id: 'shopping', label: 'Shopping', color: '#8b5cf6', icon: 'ShoppingBag' },
  { id: 'transportation', label: 'Transportation', color: '#3b82f6', icon: 'Car' },
  { id: 'subscriptions', label: 'Subscriptions', color: '#ec4899', icon: 'RefreshCw' },
  { id: 'bills_utilities', label: 'Bills & Utilities', color: '#6366f1', icon: 'Zap' },
  { id: 'entertainment', label: 'Entertainment', color: '#f43f5e', icon: 'Gamepad2' },
  { id: 'health_fitness', label: 'Health & Fitness', color: '#10b981', icon: 'Heart' },
  { id: 'travel', label: 'Travel', color: '#0ea5e9', icon: 'Plane' },
  { id: 'income', label: 'Income', color: '#22c55e', icon: 'TrendingUp' },
  { id: 'transfer', label: 'Transfer', color: '#94a3b8', icon: 'ArrowLeftRight' },
  { id: 'other', label: 'Other', color: '#64748b', icon: 'MoreHorizontal' },
];

export const MERCHANT_KEYWORDS: Record<string, Category> = {
  // Food & Dining
  'doordash': 'food_dining',
  'uber eats': 'food_dining',
  'grubhub': 'food_dining',
  'postmates': 'food_dining',
  'mcdonalds': 'food_dining',
  'starbucks': 'food_dining',
  'chipotle': 'food_dining',
  'subway': 'food_dining',
  'dominos': 'food_dining',
  'panera': 'food_dining',
  'chick-fil-a': 'food_dining',
  'wendys': 'food_dining',
  'taco bell': 'food_dining',
  'dunkin': 'food_dining',
  'pizza hut': 'food_dining',
  'panda express': 'food_dining',
  'five guys': 'food_dining',
  'shake shack': 'food_dining',
  'sweetgreen': 'food_dining',
  'cava': 'food_dining',
  'restaurant': 'food_dining',
  'cafe': 'food_dining',
  'coffee': 'food_dining',
  'grill': 'food_dining',
  'kitchen': 'food_dining',
  'diner': 'food_dining',
  'pizzeria': 'food_dining',
  'bakery': 'food_dining',
  
  // Groceries
  'whole foods': 'groceries',
  'trader joe': 'groceries',
  'safeway': 'groceries',
  'kroger': 'groceries',
  'costco': 'groceries',
  'walmart': 'groceries',
  'target': 'groceries',
  'aldi': 'groceries',
  'publix': 'groceries',
  'wegmans': 'groceries',
  'sprouts': 'groceries',
  'h-e-b': 'groceries',
  'heb': 'groceries',
  'food lion': 'groceries',
  'giant': 'groceries',
  'stop & shop': 'groceries',
  'albertsons': 'groceries',
  'instacart': 'groceries',
  'amazon fresh': 'groceries',
  'grocery': 'groceries',
  
  // Shopping
  'amazon': 'shopping',
  'best buy': 'shopping',
  'apple store': 'shopping',
  'apple.com': 'shopping',
  'ebay': 'shopping',
  'etsy': 'shopping',
  'ikea': 'shopping',
  'home depot': 'shopping',
  'lowes': 'shopping',
  'wayfair': 'shopping',
  'nordstrom': 'shopping',
  'macys': 'shopping',
  'kohls': 'shopping',
  'tj maxx': 'shopping',
  'marshalls': 'shopping',
  'ross': 'shopping',
  'old navy': 'shopping',
  'gap': 'shopping',
  'zara': 'shopping',
  'h&m': 'shopping',
  
  // Transportation
  'uber': 'transportation',
  'lyft': 'transportation',
  'shell': 'transportation',
  'chevron': 'transportation',
  'exxon': 'transportation',
  'bp': 'transportation',
  'parking': 'transportation',
  'metro': 'transportation',
  'transit': 'transportation',
  'mta': 'transportation',
  'bart': 'transportation',
  'caltrain': 'transportation',
  'gas': 'transportation',
  'speedway': 'transportation',
  'wawa': 'transportation',
  'tesla': 'transportation',
  'ridepanda': 'transportation',
  
  // Subscriptions
  'netflix': 'subscriptions',
  'spotify': 'subscriptions',
  'hulu': 'subscriptions',
  'disney+': 'subscriptions',
  'disney plus': 'subscriptions',
  'hbo': 'subscriptions',
  'max': 'subscriptions',
  'apple music': 'subscriptions',
  'youtube premium': 'subscriptions',
  'youtube music': 'subscriptions',
  'amazon prime': 'subscriptions',
  'prime video': 'subscriptions',
  'adobe': 'subscriptions',
  'microsoft 365': 'subscriptions',
  'dropbox': 'subscriptions',
  'icloud': 'subscriptions',
  'google one': 'subscriptions',
  'chatgpt': 'subscriptions',
  'openai': 'subscriptions',
  'anthropic': 'subscriptions',
  'notion': 'subscriptions',
  'figma': 'subscriptions',
  'canva': 'subscriptions',
  'linkedin premium': 'subscriptions',
  'audible': 'subscriptions',
  'kindle': 'subscriptions',
  
  // Bills & Utilities
  'at&t': 'bills_utilities',
  'verizon': 'bills_utilities',
  't-mobile': 'bills_utilities',
  'comcast': 'bills_utilities',
  'xfinity': 'bills_utilities',
  'spectrum': 'bills_utilities',
  'electric': 'bills_utilities',
  'water': 'bills_utilities',
  'gas bill': 'bills_utilities',
  'pge': 'bills_utilities',
  'con edison': 'bills_utilities',
  'duke energy': 'bills_utilities',
  'texas gas': 'bills_utilities',
  'city of austin': 'bills_utilities',
  'austin mud': 'bills_utilities',
  'insurance': 'bills_utilities',
  'geico': 'bills_utilities',
  'state farm': 'bills_utilities',
  'progressive': 'bills_utilities',
  'allstate': 'bills_utilities',
  'prog county mut': 'bills_utilities',
  
  // Entertainment
  'steam': 'entertainment',
  'playstation': 'entertainment',
  'xbox': 'entertainment',
  'nintendo': 'entertainment',
  'movie': 'entertainment',
  'cinema': 'entertainment',
  'amc': 'entertainment',
  'regal': 'entertainment',
  'concert': 'entertainment',
  'ticketmaster': 'entertainment',
  'stubhub': 'entertainment',
  'vivid seats': 'entertainment',
  
  // Health & Fitness
  'gym': 'health_fitness',
  'planet fitness': 'health_fitness',
  'equinox': 'health_fitness',
  'orangetheory': 'health_fitness',
  'crossfit': 'health_fitness',
  'peloton': 'health_fitness',
  'cvs': 'health_fitness',
  'walgreens': 'health_fitness',
  'pharmacy': 'health_fitness',
  'rite aid': 'health_fitness',
  'doctor': 'health_fitness',
  'medical': 'health_fitness',
  'dental': 'health_fitness',
  'modern animal': 'health_fitness',
  
  // Travel
  'airline': 'travel',
  'hotel': 'travel',
  'marriott': 'travel',
  'hilton': 'travel',
  'hyatt': 'travel',
  'airbnb': 'travel',
  'vrbo': 'travel',
  'expedia': 'travel',
  'booking.com': 'travel',
  'united': 'travel',
  'delta': 'travel',
  'american air': 'travel',
  'southwest': 'travel',
  'jetblue': 'travel',
  'frontier': 'travel',
  'spirit': 'travel',
  'wise': 'travel',
};

